GET {{content_host}}/content/course-category/tree-nodes

###
GET {{system_host}}/system/dictionary/all
Accept: application/json

###
<> 2023-10-02T220008.404.html
### 查询课程信息
POST {{content_host}}/content/course/list?pageNo=1&pageSize=2
Content-Type: application/json

{
  "auditStatus": "",
  "courseName": "java",
  "publishStatus": ""
}
<> 2023-10-02T220434.200.json

### 创建课程
POST {{content_host}}/content/course
Content-Type: application/json

{
  "charge": "201001",
  "price": 1110,
  "originalPrice":110,
  "qq": "22333",
  "wechat": "223344",
  "phone": "13333333",
  "validDays": 365,
  "mt": "",
  "st": "1-1-1",
  "name": "测试测试java,java测试",
  "pic": "avdfdfad",
  "teachmode": "200002",
  "users": "初级人员",
  "tags": "tags",
  "grade": "204001",
  "description": "Java_yujian_讲课Java_yujian_讲课Java_yujian_讲课Java_yujian_讲课"
}

### 根据课程id查询课程信息
GET {{content_host}}/content/course/2
Content-Type: application/json

### 修改课程
PUT {{content_host}}/content/course
Content-Type: application/json

{
  "id": 40,
  "name": "SpringBoot核心_yujian123",
  "users": "Spring Boot初学者_yujian123",
  "tags": "Spring项目的快速构建_yujian123",
  "mt": "1-3",
  "st": "1-3-2",
  "grade": "200003",
  "teachmode": "201001",
  "description": "课程系统性地深度探讨 Spring Boot 核心特性，引导小伙伴对 Java 规范的重视，启发对技术原理性的思考，掌握排查问题的技能，以及学习阅读源码的方法和技巧，全面提升研发能力，进军架构师队伍。",
  "pic": "https://cdn.educba.com/academy/wp-content/uploads/2018/08/Spring-BOOT-Interview-questions.jpg",
  "charge": "201001",
  "price": 0.01
}

### 查询某个课程的课程计划
GET {{content_host}}/content/teachplan/117/tree-nodes

### 课程课程计划,需要从数据库找到修改的课程计划id
POST {{content_host}}/content/teachplan
Content-Type: application/json

{
  "changeDate" : null,
  "courseId" : 1,
  "cousePubId" : null,
  "createDate" : null,
  "ctlBarShow" : false,
  "ctlEditTitle" : true,
  "endTime" : null,
  "grade" : "2",
  "isPreview" : "1",
  "mediaType" : "",
  "orderby" : 1,
  "parentid" : 255,
  "pname" : "新小节名称1",
  "startTime" : null,
  "status" : null,
  "teachPlanId" : 240
}

### 删除课程计划
DELETE {{content_host}}/content/teachplan/293